name: Regenerate Resource Files

on:
  push:
    paths:
      - ".github/workflows/resources.yml"
      - "res/**"
      - "tools/generate-assets.sh"
  workflow_dispatch:

jobs:
  build-pr:
    name: Regenerate Resource Files
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate Assets
        run: tools/generate-assets.sh